name: 'Env File Updater'
author: "Melchizedek Logosu"
description: 'This Github Action will allow you to pass array of key-value pairs and will use them to update a target file'
inputs:
  file_name:
    description: 'Name of the file to be updated including the path of the file'
    required: true
  data:
    description: 'Dictionary of key-value pairs'
    required: true
  separator:
    description: 'the assignment operator to be used to separate the key-values eg. mel=code. default is ='
    required: false
    default: "="
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_name }}
    - ${{ inputs.data }}
    - ${{ inputs.separator }}
