on: [ push ]

jobs:
  env_file_updater_job:
    runs-on: [ self-hosted, zedeks_digital ]
    name: 'A job to edit .env files'
    steps:
      - name: Hello world action step
        id: hello
        uses: Zedeks-Digital/env-file-updater@main
        with:
          file_name: './testfiles/testenv'
          data: '{ 
          "DB_DATABASE": "saprfacility_web"
          "DB_USERNAME": "root"
          "DB_PASSWORD": "@Zedeks"
          "APP_DEBUG": "mel"
          }'
          separator: ':'